[book]
language = "uk"
multilingual = false
src = "docs"

# Замініть авторство проєкта на своє
authors = ["Artur \" Yanchuk"]

# Змініть назву проєкта на свою
title = "Система управління відкритими даними"

[preprocessor.plantuml]
plantuml-cmd = "http://www.plantuml.com/plantuml"
use-data-uris = true
